In [2]:
import torch

Tensors are like arrays with special properties

In [3]:
# an array or tensor of 10 random numbers
torch.rand(10)

tensor([0.1545, 0.1199, 0.2138, 0.3806, 0.1543, 0.6272, 0.9372, 0.2559, 0.6235,
        0.9664])

In [4]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)

In [5]:
a

tensor([[0.9994, 0.0636],
        [0.1003, 0.9368]])

In [6]:
b

tensor([[0.1452, 0.1938],
        [0.9028, 0.4410]])

For simple cell-to-cell operations, use the typical commands like the ones for addition, subtraction, multiplication, etc.

In [7]:
a + b

tensor([[1.1447, 0.2574],
        [1.0032, 1.3778]])

In [8]:
a * b

tensor([[0.1451, 0.0123],
        [0.0906, 0.4131]])

For performing matrix operations, there are different operators. For example, use `@` for matrix multiplication

In [9]:
a @ b

tensor([[0.2026, 0.2218],
        [0.8604, 0.4326]])

In [11]:
# same as above
torch.mm(a, b)

tensor([[0.2026, 0.2218],
        [0.8604, 0.4326]])

In [13]:
# for tensor concatenation
torch.cat((a, b))

tensor([[0.9994, 0.0636],
        [0.1003, 0.9368],
        [0.1452, 0.1938],
        [0.9028, 0.4410]])

Getting and manipulating tensor shapes is something that will come up frequently in deep learning

In [14]:
a.shape

torch.Size([2, 2])

In [16]:
# creating a new tensor with specific values
c = torch.tensor([1.4, 0, 3.5, 2])
c.shape

torch.Size([4])

In [17]:
# will fail, since shape is different, even though the number of elements is equal
torch.cat((a, c)) 

RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 1 at /opt/conda/conda-bld/pytorch-cpu_1556653093101/work/aten/src/TH/generic/THTensor.cpp:702

- Concatenation of tensors with different shapes will fail even though the number of elements is equal.
- This can be fixed by changing the shape of the tensors before performing any operations on them.
- `tensor.view` can be used to get a temporary value of the changed shape for a tensor, which can later be saved and used
- `tensor.view` can also be used in case you are unaware of the rows or columns you need at the end. Just use `-1` to the component you don't know, and specify the other.

In [18]:
c.view(2, 2)

tensor([[1.4000, 0.0000],
        [3.5000, 2.0000]])

In [19]:
# original shape is not changed
c

tensor([1.4000, 0.0000, 3.5000, 2.0000])

In [20]:
# now we can use this value to concatenate with a
torch.cat((a, c.view(2, 2)))

tensor([[0.9994, 0.0636],
        [0.1003, 0.9368],
        [1.4000, 0.0000],
        [3.5000, 2.0000]])

In [24]:
c.view(4, -1)

tensor([[1.4000],
        [0.0000],
        [3.5000],
        [2.0000]])