In [1]:
import torch

In [3]:
a = torch.zeros(3, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
b = torch.ones(3, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
c = torch.cat((a, b), dim = 1)
c

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [8]:
c.shape

torch.Size([3, 6])

In [9]:
c.type()

'torch.FloatTensor'

In [10]:
# changing the type of tensor from float to long
c.type(torch.LongTensor)

tensor([[0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 1]])

In [12]:
d = torch.rand(3, 100, 100)
d

tensor([[[0.8534, 0.2827, 0.1455,  ..., 0.7155, 0.3262, 0.2578],
         [0.8304, 0.5645, 0.3075,  ..., 0.6169, 0.3781, 0.2910],
         [0.7230, 0.3419, 0.1034,  ..., 0.4775, 0.8692, 0.9134],
         ...,
         [0.6476, 0.1874, 0.0536,  ..., 0.3043, 0.2825, 0.3217],
         [0.0640, 0.9307, 0.3926,  ..., 0.2249, 0.7285, 0.1503],
         [0.7534, 0.2053, 0.7048,  ..., 0.6685, 0.9207, 0.6015]],

        [[0.8252, 0.8862, 0.1163,  ..., 0.6171, 0.4478, 0.7309],
         [0.6459, 0.6679, 0.2590,  ..., 0.1403, 0.8739, 0.1399],
         [0.3256, 0.7727, 0.8151,  ..., 0.9731, 0.7508, 0.8197],
         ...,
         [0.9360, 0.5423, 0.6826,  ..., 0.3288, 0.9179, 0.7844],
         [0.4941, 0.2397, 0.9831,  ..., 0.2342, 0.4242, 0.3802],
         [0.0973, 0.8064, 0.0305,  ..., 0.2988, 0.3032, 0.3412]],

        [[0.3188, 0.8391, 0.3463,  ..., 0.0808, 0.2498, 0.5146],
         [0.4657, 0.1667, 0.9211,  ..., 0.9359, 0.0293, 0.8625],
         [0.8060, 0.2911, 0.9725,  ..., 0.2239, 0.1019, 0.

In [13]:
# mean of d
torch.mean(d)

tensor(0.4994)

In [14]:
# standard deviation of d
torch.std(d)

tensor(0.2895)